module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

services:
  googleAnalytics:
    ID: G-XG3WNT68QZ

baseURL: "https://chrisclarkson.org"
mainsections:
  - posts

languages:
  en:
    title: chrisclarkson.org
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Profile
          weight: 1
          url: /profile/
        - name: Blog
          weight: 2
          url: /posts/
        - name: Tags
          weight: 3
          url: /tags/
          enableRobotsTXT: true
          paginate: 20

params:
  env: production
  home: Home
  keywords:
    - blog
    - developer
    - engineer
    - security
    - hacker
    - hacking
    - cloud
    - AWS
    - GCP
  avatarurl: /images/chrisclarkson.jpg
  DataFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false
  hideCredits: false
  hideCopyright: false
  itemscentered: true
  rtl: false
  snsShare: true
  langseparator: "|"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  profileMode:
    enabled: true
    title: Chris Clarkson
    subtitle: >-
      Experienced Security Architect & Engineer | Vulnerability Management, Cloud and Supply Chain Security | Security Built in Not Bolted On!
    imageUrl: /images/chrisclarkson.jpg
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: /posts
      - name: Tags
        url: /tags
  socialIcons:
    - name: Github
      weight: 1
      url: "https://github.com/ClarksonCJ/"
    - name: Gitlab
      weight: 2
      url: "https://gitlab.com/clarksoncj"
    - name: BlueSky
      weight: 3
      url: "https://bsky.app/profile/clarksoncj.bsky.social"
    - name: Mastodon
      weight: 4
      url: "https://infosec.exchange/@ClarksonCJ"
    - name: LinkedIn
      weight: 5
      url: "https://www.linkedin.com/in/cjclarkson/"
  assets:
    favicon: favicon.png
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: favicon.png
    safari_pinned_tab: favicon.png
